### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by MrRetroChannel** [jchallenger1/Simple-Reddit-for-C-plus-plus#2]
Hey, I know, it's kind of dead thing, but could you please help me with proper installment on windows? I would be shitting myself if you would help me. Thanks!

**Comment by jchallenger1** [comment]
Hey MrRetroChannel!

Here is what I did to make this working on windows, using Visual Studio 2019:
1. Copy this repo and create a new project
2. Use Visual studio directly to add in the files under /include and /src into the project by using Project Name -> Existing Item
3. Create the libcurl library, use [this](https://stackoverflow.com/questions/30288415/curl-with-visual-studio-2013) resource as a reference how to do this, below is more explanation/steps that I changed:

   1. Download the source archive, curl-7.77.0.zip
   2. No need to go to the path for the Visual Studio command prompt, you can use the terminal in Visual Studio, under Top toolbar -> View -> Terminal or Ctrl+`
   3. Run the nmake command under \<curlExportDirectory>\curl\winbuild
   4. Instead of \builds\libcurl-vc-x86-release-dll-ipv6-sspi-winssl, use \builds\libcurl-vc-x86-release-dll-ipv6-sspi-schannel
   5. Add \curl-7.42.1\builds\release\include to Project->Configuration Properties->C/C++->General->Additional Include Directories
   6. (Optional, depending on config) Add in this repo's include directory to both Project->Configuration Properties->C/C++->General->Additional Include Directories & VC++ Directories > Include directories
   7. Add the following code

```C++
#undef max
#undef min
```
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; To include\json.hpp

I would like to point out that I would **strongly recommend not** to use this library due to the above hacks on the json file to even run the library, and most importantly the development scope of this repo. If you are looking for a more complete reddit api solution, I would suggest Python's [PRAW](https://praw.readthedocs.io/en/latest/) library containing extensive documentation, of which you could link with a C++ program through either IPC mechanisms, running a python script directly in code or other python embedded C++ solutions.

I hope this helps you out.

**Comment by MrRetroChannel** [comment]
Thanks a lot, now it's working

**Comment by jchallenger1** [comment]
Glad to hear!
